#!/bin/bash

cd $(dirname $BASH_SOURCE)

export GIT_SSL_NO_VERIFY=true
mkdir -p ~/.vim/autoload
curl -k -k -fL -o ~/.vim/autoload/plug.vim https://raw.github.com/junegunn/vim-plug/master/plug.vim

# vimrc
mv -v ~/.vimrc ~/.vimrc.old 2> /dev/null
ln -sf `pwd`/vimrc ~/.vimrc

vim +PlugInstall +qall

