#!/bin/bash
#
# Junegunn Choi (junegunn.c@gmail.com)
# 2011/05/25-

# RC files

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

BASE=$(pwd)
touch bashrc-extra
for rc in *rc *profile tmux.conf agignore rubocop.yml; do
  mkdir -pv bak
  [ -e ~/."$rc" ] && mv -v ~/."$rc" bak/."$rc"
  ln -sfv "$BASE/$rc" ~/."$rc"
done

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
fi

# scripts
mkdir -p ~/bin
for bin in $BASE/bin/*; do
  ln -svf "$bin" ~/bin
done

# leiningen
mkdir -p ~/.lein
ln -sfv "$BASE/profiles.clj" ~/.lein/

if [ "$(uname -s)" = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Updating homebrew"
  brew install \
    fd ag ripgrep ant cmus coreutils cscope exiftool doxygen liboauth \
    fish git graphviz imagemagick leiningen sbt \
    maven ranger tree vim wget zsh jq macvim ruby python go highlight reattach-to-user-namespace
  brew install gnuplot --with-qt --with-cairo

  # Patched version of tmux
  brew tap waltarix/homebrew-customs
  brew install waltarix/homebrew-customs/tmux

  command -v blsd > /dev/null ||
    (bash <(curl -fL https://raw.githubusercontent.com/junegunn/blsd/master/install) && mv blsd ~/bin)

  # Create
  gem install gem-ctags
  gem ctags

  brew tap universal-ctags/universal-ctags
  brew install --HEAD universal-ctags

  brew cask install xquartz iterm2-nightly spectacle virtualbox virtualbox-extension-pack \
    vagrant mat visualvm spotifree flux flycut keycastr fluid
else
  rm -f ~/.tmux.conf
  grep -v reattach-to-user-namespace tmux.conf > ~/.tmux.conf
fi

git config --global user.email "junegunn.c@gmail.com"
git config --global user.name "Junegunn Choi"

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
tmux source-file ~/.tmux.conf

./install-vim
