#!/bin/bash
#
# Junegunn Choi (junegunn.c@gmail.com)
# 2011/05/25-

# RC files
cd $(dirname $BASH_SOURCE)
BASE=$(pwd)
touch bashrc-extra
for rc in *rc *profile tmux.conf agignore; do
  mkdir -pv bak
  [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
  ln -sfv $BASE/$rc ~/.$rc
done

# git-prompt
if [ ! -e ~/.git-prompt.sh ]; then
  curl https://raw.github.com/git/git/master/contrib/completion/git-prompt.sh \
    -o ~/.git-prompt.sh
fi

# scripts
mkdir -p ~/bin
for bin in $BASE/bin/*; do
  ln -svf $bin ~/bin
done

# leiningen
mkdir -p ~/.lein
ln -sfv $BASE/profiles.clj ~/.lein/

if [ $(uname -s) = 'Darwin' ]; then
  # Homebrew
  [ -z "$(which brew)" ] &&
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  echo "Updating homebrew"
  brew update
  brew install \
    ag ant cmus coreutils cscope ctags \
    fish git gnuplot graphviz imagemagick leiningen \
    maven memcached mysql redis \
    sl tmux tree unrar vim wget zsh
  brew install macvim
fi

git config --global user.email "junegunn.c@gmail.com"
git config --global user.name "Junegunn Choi"

tmux source-file ~/.tmux.conf

./install-vim
